### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by chengpeixin** [RenRongrong/pandyle#5]
页面初始化时花括号会首先渲染，这部分处理了吗？

**Comment by RenRongrong** [comment]
因为pandyle是在dom加载完成后才进行渲染的，所以一开始是会出现花括号的。要解决这个问题，可以一开始给元素设置为隐藏，在vm()方法之后再将其显示出来。也可以将内容都放在组件里面，组件中的内容是渲染好之后再显示的。

**Comment by chengpeixin** [comment]
好的，明白了，谢谢
